-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 17:40:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProyectoFinal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectoFinal` ;

-- -----------------------------------------------------
-- Schema ProyectoFinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoFinal` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoFinal` ;

-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Categories` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Categories` (
  `id` INT NOT NULL,
  `Category_Name` VARCHAR(45) NOT NULL,
  `Category_Creation` TIMESTAMP NOT NULL,
  `Category_User_Creator` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Contact` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Contact` (
  `usuario_idusuario` INT NOT NULL AUTO_INCREMENT,
  `id` INT NOT NULL,
  `country` VARCHAR(40) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `State/Comuna` VARCHAR(45) NOT NULL,
  `Direction` VARCHAR(45) NOT NULL,
  `Village` VARCHAR(45) NULL,
  `Direction_Number` INT NOT NULL,
  `Depto_Number` INT NULL,
  `Telephone` INT NULL,
  `Celphone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `id`));

-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Log_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Log_usuario` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Log_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Accion` VARCHAR(100) NOT NULL,
  `Error` VARCHAR(100) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Person` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(45) NOT NULL,
  `Last_Name` VARCHAR(45) NOT NULL,
  `Rut` INT NOT NULL,
  `BirthDay` VARCHAR(45) NOT NULL,
  `Contact_usuario_idusuario` INT NOT NULL,
  `Contact_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Contact_usuario_idusuario`, `Contact_id`));


-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Request` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Request` (
  `id` INT NOT NULL,
  `Categories_id` INT NOT NULL,
  `User` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(150) NOT NULL,
  `Date` DATE NOT NULL,
  `Time` TIMESTAMP NOT NULL,
  `Price` FLOAT NOT NULL,
  `Categoria` VARCHAR(15) NOT NULL,
  `Status` VARCHAR(10) NOT NULL,
  `Contact_usuario_idusuario` INT NOT NULL,
  `Contact_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Categories_id`));


-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Request_History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Request_History` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Request_History` (
  `id` INT NOT NULL,
  `Request_Id` INT NOT NULL,
  `User` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(150) NOT NULL,
  `Price` INT NOT NULL,
  `User_Solicitude` VARCHAR(45) NOT NULL,
  `Wall_requests_has_Request_Solicitud_Wall_requests_id` INT NOT NULL,
  `Wall_requests_has_Request_Solicitud_Request_Solicitud_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Wall_requests_has_Request_Solicitud_Wall_requests_id`, `Wall_requests_has_Request_Solicitud_Request_Solicitud_id`));


-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Request_Solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Request_Solicitud` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Request_Solicitud` (
  `id` INT NOT NULL,
  `User_Name` VARCHAR(45) NOT NULL,
  `User_Id` INT NOT NULL,
  `User_Description` VARCHAR(150) NOT NULL,
  `User_Price` FLOAT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Contact_usuario_idusuario` INT NOT NULL,
  `Contact_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Contact_usuario_idusuario`, `Contact_id`));


-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Roles` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Wall_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Wall_requests` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Wall_requests` (
  `id` INT NOT NULL,
  `Solicitud_id` INT NOT NULL,
  `Solicitud_Categories_id` INT NOT NULL,
  `Request_Name` VARCHAR(45) NOT NULL,
  `Request_Description` VARCHAR(45) NOT NULL,
  `Request_Category` VARCHAR(45) NOT NULL,
  `Name_Solicitud` VARCHAR(45) NOT NULL,
  `Description_Solicitud` VARCHAR(150) NOT NULL,
  `Price` FLOAT NOT NULL,
  `Wall_requestscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ProyectoFinal`.`Wall_requests_has_Request_Solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`Wall_requests_has_Request_Solicitud` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`Wall_requests_has_Request_Solicitud` (
  `Wall_requests_id` INT NOT NULL,
  `Request_Solicitud_id` INT NOT NULL,
  PRIMARY KEY (`Wall_requests_id`, `Request_Solicitud_id`));


-- -----------------------------------------------------
-- Table `ProyectoFinal`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectoFinal`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ProyectoFinal`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `ImagePerfil` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `Request_History_id` INT NOT NULL,
  `Request_History_Wall_requests_has_Request_Solicitud_Wall_requests_id` INT NOT NULL,
  `Request_History_Wall_requests_has_Request_Solicitud_Request_Solicitud_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Request_History_id`, `Request_History_Wall_requests_has_Request_Solicitud_Wall_requests_id`, `Request_History_Wall_requests_has_Request_Solicitud_Request_Solicitud_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
